config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: 'registrations', omniauth_callbacks: 'callbacks'}
  root to: 'application#welcome'
  get 'memorabilias/search_term/:search_term', to: 'memorabilias#index'
  get 'memorabilias/cheap', to: 'memorabilias#cheap'
  resources :memorabilias 
  resources :athletes, execpt: [:edit, :update, :destroy] do 
    get 'memorabilias/cheapest', to: 'memorabilias#cheapest'
    resources :memorabilias
  end
  
 

  devise_scope :user do
    get 'login', to: 'devise/sessions#new', as: 'login' 
    get 'signup', to: 'devise/registrations#new', as: 'signup'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/athlete.rb
class Athlete < ApplicationRecord
    has_many :memorabilias
    has_many :users, through: :memorabilias

    validates :name, :team, presence: true

    def self.search(query)
        if query
            self.where('name LIKE ?', "%#{query}%")
        else
            self.all
        end
    end
end

app/models/memorabilia.rb
class Memorabilia < ApplicationRecord
    belongs_to :user
    belongs_to :athlete
    accepts_nested_attributes_for :athlete, reject_if: proc {|attributes| attributes['name'].blank?}
    validates :item_type, :price, presence: true

    scope :expensive, -> { where("price > 100") }
    scope :cheap, -> { order(price: :asc) }
    scope :cheapest, -> { includes(:athlete).order(price: :asc).limit(1) } 
    # scope :cheapest, -> { cheap.limit(1) }

    def self.search(query)
        if query
            self.where('item_type LIKE ?', "%#{query}%")
        else
            self.all
        end
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable

  has_many :memorabilias
  has_many :athletes, through: :memorabilias

  validates :username, :email,  uniqueness: true
  validates :username, :email, :password, :password_confirmation, presence: true
  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.username = auth.info.name
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0...20]  
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :require_login
    add_flash_types :info, :error, :warning
    
    def welcome
        if user_signed_in?
            @user = current_user
        end
    end

    def require_login
        unless current_user
          redirect_to root_url
        end
    end
end

app/controllers/athletes_controller.rb
class AthletesController < ApplicationController
    before_action :set_athlete, only: [:show]
    before_action :authenticate_user!
    
    def index
        @athletes = current_user.athletes.search(params[:query]).uniq(&:name)
    end

    def create
        @athlete = current_user.athletes.build(athlete_params)
        if @athlete.save
            redirect_to @athlete
        else
            render :new
        end
    end

    def show
        if @athlete.nil?
            redirect_to athletes_path, alert: "Athlete not found!"
        else
            @memorabilias = @athlete.memorabilias
        end
    end

    private 

    def set_athlete
        @athlete = current_user.athletes.find_by(id: params[:id])
    end

    def athlete_params
        params.require(:athlete).permit(:name, :team, :active)
    end
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
    def github
        @user = User.from_omniauth(request.env["omniauth.auth"])
        
        sign_in_and_redirect @user
    end
end

app/controllers/memorabilias_controller.rb
class MemorabiliasController < ApplicationController
    before_action :set_athlete, except: [:new, :index]
    before_action :set_memorabilia, only: [:edit, :update, :destroy]
    before_action :authenticate_user!

    def index
      if params[:athlete_id]
        set_athlete
          if @athlete.nil?
            redirect_to root_path, alert: "Athlete not found"
          else
              @memorabilias = @athlete.memorabilias.search(params[:query])
          end
      elsif params[:search_term]
        if params[:search_term] == "expensive"
          @memorabilias =  current_user.memorabilias.expensive
        end
      else
        @memorabilias = current_user.memorabilias.search(params[:query])
      end
    end

    def new
      if params[:athlete_id]
        set_athlete
        @memorabilia = @athlete.memorabilias.build
      else  
        @memorabilia = current_user.memorabilias.build
        @athlete = @memorabilia.build_athlete
      end
    end

    def create
      @memorabilia = current_user.memorabilias.build(memorabilia_params)
      if @memorabilia.save
        redirect_to @memorabilia
      else
        render :new
      end
    end

    def cheapest
      if params[:athlete_id]
        set_athlete
          if @athlete.nil?
            redirect_to root_path, alert: "Athlete not found"
          else
            if @athlete.memorabilias.nil?
              redirect_to athlete_path, alert: "Memorabilias not found"
            else
              @memorabilia = Memorabilia.where(user_id: current_user.id, athlete_id: params[:athlete_id])
              @memorabilia = @memorabilia.cheapest[0]
            end
          end
      end
    end

    def cheap
      @memorabilias =  current_user.memorabilias.cheap
    end

    def show
      if params[:athlete_id]
        set_athlete
          if @athlete.nil?
            redirect_to root_path, alert: "Athlete not found"
          else
            @memorabilia = @athlete.memorabilias.find_by(id: params[:id])
          end
      else
         set_memorabilia
       end
    end

    def edit
      if params[:athlete_id]
        set_athlete
          if @athlete.nil?
            redirect_to root_path, alert: "Athlete not found"
          else
            @memorabilia = @athlete.memorabilias.find_by(id: params[:id])
          end
      else
          set_memorabilia
       end
    end

    def update
        @memorabilia.update(memorabilia_params)
        if @memorabilia.save
          redirect_to athlete_memorabilia_path(@memorabilia.athlete, @memorabilia)
        else
          render :edit
        end
    end

    def destroy
        set_athlete
        @memorabilia = @athlete.memorabilias.find_by(id: params[:id])
        @memorabilia.destroy
        redirect_to athlete_memorabilias_path(@athlete)
    end

    private


    def set_athlete
      @athlete = current_user.athletes.find_by(id: params[:athlete_id])
    end

    def set_memorabilia
      @memorabilia = current_user.memorabilias.find_by(id: params[:id])
    end

    def memorabilia_params
        params.require(:memorabilia).permit(:user_id, :athlete_id, :price, :autographed, :item_type, athlete_attributes: [
          :name,
          :team,
          :active
       ])
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    private
    def sign_up_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
    
    def account_update_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
end
    

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/athletes_helper.rb
module AthletesHelper
    
end

app/helpers/callbacks_helper.rb
module CallbacksHelper
end

app/helpers/memorabilias_helper.rb
module MemorabiliasHelper
  def athlete_select(memorabilia)
    select_tag 'memorabilia[athlete_id]', options_from_collection_for_select(Athlete.all, :id, :name), :include_blank => true
  end
end

app/views/application/welcome.html.erb
<h2>Welcome to My Memorabilia</h2>

<% if user_signed_in? %>
    <ul>
        <li><%= "Welcome, #{ @user.username }" %></li>
        <li><%= link_to 'Memorabilias', memorabilias_path %></li>
        <li><%= link_to 'Athletes', athletes_path %></li>
    </ul>
<% else %>
    <p> Please Signin or Signup for our app please!!! </p>
<% end %>

app/views/athletes/_athlete.html.erb
<h2><%= @athlete.name %></h2>

<p>Last known team played for:</p>
<p><%= @athlete.team %></p>

<p>Still Active?</p>
<p><%= @athlete.active %></p>

app/views/athletes/index.html.erb
<%= form_tag athletes_path, method: :get do %>
       <%= render 'memorabilias/query' %>
<% end %>
<% @athletes.each do |athlete| %>
        <%= link_to athlete.name , athlete_memorabilias_path(athlete) %><br>
<% end %>
<br>
<button><%= link_to "Home", root_path %></button>

app/views/athletes/new.html.erb
<h1>Create New Athlete</h1>

<%= render partial: 'form' %>

app/views/athletes/show.html.erb
<%= render partial: 'athlete' %>

<h3>Here's the memorabilias you have of this athlete!!</h3>
<%= render(@memorabilias) %>

app/views/layouts/_nav.html.erb
<nav>
    <ul>
        <li><%= link_to 'Home', root_path %></li>
        <% if !user_signed_in? %>
            <li><%= link_to 'Signup', new_user_registration_path %></li>
            <li><%= link_to 'Signin', new_user_session_path %></li>
        <% else %>
            <li><%= button_to 'Logout', destroy_user_session_path, method: "delete" %></li>
            <li> <%= current_user.username %> </li>
        <% end %>
    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyMemorabilia</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/nav'%> 
  <% flash.each do |name, msg| -%>
      <%= content_tag :div, msg, class: name %>
  <% end -%>
    <%= yield %>
  </body>
</html>

app/views/memorabilias/_errors.html.erb
<div id="error_explanation">
    <h2><%= pluralize(memorabilia.errors.count, "error") %> prohibited this memorabilia from being saved:</h2>
    <ul>
        <% memorabilia.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
</div>

app/views/memorabilias/_form.html.erb
<% if @memorabilia.errors.any? %>
  <%= render partial: 'errors', locals: {memorabilia: @memorabilia}%>
<% end %>
<%= form_for(@memorabilia) do |f| %>
  <%= f.label :item_type %>
  <%= f.text_field :item_type %>
  <br>
  <%= f.label :price %>
  <%= f.number_field :price %>
  <br>
  <%= f.label :autographed %>
  <%= f.check_box :autographed %>
  <br>
  <% if params[:athlete_id] %>
        <%= f.hidden_field :athlete_id %>
    <% else %>
        <h3>Select an existing athlete</h3>
        <%= athlete_select(@memorabilia) %>
        <p> Or create a new one <br><br>
        <%= f.fields_for :athlete, @athlete do |ath| %>
            <%= ath.text_field :name, placeholder: "Name" %>
            <%= ath.text_field :team, placeholder: "Team" %>
            <%= ath.label :active %>
            <%= ath.check_box :active %>
        <% end %></p>
    <% end %>
    <%= f.submit class: "btn btn-secondary btn-sm text-white" %>
<% end %>

app/views/memorabilias/_memorabilia.html.erb
<%= link_to "$#{memorabilia.price} - #{memorabilia.athlete.name}\'s #{memorabilia.item_type}", athlete_memorabilia_path(memorabilia.athlete, memorabilia) %>
<%= link_to 'Edit', edit_athlete_memorabilia_path(memorabilia.athlete, memorabilia) %><br>

app/views/memorabilias/_query.html.erb
<p>
    <%= text_field_tag :query, params[:query] %>
    <%= submit_tag "Search", name: nil %>
</p>

app/views/memorabilias/cheap.html.erb
<%= render(@memorabilias) %>

app/views/memorabilias/cheapest.html.erb
<h2>You are viewing <%= @memorabilia.athlete.name %>'s cheapest memorabilia</h2>
<ul>
    <%= render partial: 'memorabilia', locals: {memorabilia: @memorabilia} %>
</ul>
<%= link_to "Back", athlete_memorabilias_path(@memorabilia.athlete) %>

app/views/memorabilias/edit.html.erb
<h1>You are editing <%= @athlete.name %>'s <%= @memorabilia.item_type %>.</h1>

<%= render partial: 'form' %>

app/views/memorabilias/index.html.erb
<% if @athlete %>
    <h2>Here's the memorabilia you have of <%= @athlete.name %></h2>
    <%= form_tag athlete_memorabilias_path, method: :get do %>
       <%= render 'query' %>
    <% end %>
<% else %>
    <h2>Here these are what you have in your collection!!</h2>
    <%= form_tag memorabilias_path, method: :get do %>
       <%= render 'query' %>
    <% end %>
<% end %>

<% if @memorabilias.nil? %>
<h3>Please record your Memorabilia now!!</h3>
<% else %>
    <ul>
    <% @memorabilias.each do |m|%>
        <%= link_to "$#{m.price} - #{m.athlete.name}\'s #{m.item_type}", athlete_memorabilia_path(m.athlete, m) %>
        <%= link_to 'Edit', edit_athlete_memorabilia_path(m.athlete, m) %><br>
    <% end %>
    </ul>
    <%= link_to 'Cheap Memorabilias', memorabilias_cheap_path %>
<% end %>
<% if @athlete %>
    <%= link_to 'New Memorabilia', new_athlete_memorabilia_path(@athlete) %>
    <%= link_to 'Cheapest Memorabilia', athlete_memorabilias_cheapest_path(@athlete.id) %>
    <%= link_to "Back", athletes_path %>
<% else %>
    <%= link_to 'New Memorabilia', new_memorabilia_path %><br>
    <%= link_to 'Expensive Memorabilias', '/memorabilias/search_term/expensive' %>
<% end %>

app/views/memorabilias/new.html.erb
<h1>Make Your Memorabilia here!!</h1>

<%= render partial: 'form' %>

app/views/memorabilias/show.html.erb
<h2><%= link_to @memorabilia.athlete.name, athlete_path(@memorabilia.athlete) %>'s <%= @memorabilia.item_type %></h1>
<p>Click the athlete's name above to visit their page</p>
<p>Price: </p>
<p>$<%= @memorabilia.price %></p><br>
<p>Autographed?: </p>
<p><%= @memorabilia.autographed.to_s.capitalize %></p>

<%= link_to 'Edit This Memorabilia',  edit_athlete_memorabilia_path(@memorabilia.athlete, @memorabilia) %><br>
<%= button_to "Delete This Memorabilia", athlete_memorabilia_path(@memorabilia.athlete_id, @memorabilia.id), method: :delete %><br>
<%= link_to "Back", athlete_memorabilias_path(@memorabilia.athlete) %>